### PR TITLE
Feature/outstanding examples

### PR DESCRIPTION
**Pull request by robert-duda-cap**
Ready for CR.

First step of unification done.
Override methods from Page Objects had been unified.
Also all left / outstanding / missing Page Objects for pages without tests were added for future use.

### CODE REVIEW

**Comment by robert-duda-cap** [comment]
@lstefaniszyn : thank you very much, and that is a good point to run them on Jenkins
@mchudzik : please let me know when you are available to talk, e.g. by gitter

**Comment by lstefaniszyn** [comment]
@robert-duda-cap: Here is our tmp jenkins http://10.40.234.40:8080/job/MrChecker-SDLC/

**Comment by robert-duda-cap** [comment]
[site.zip](https://github.com/devonfw/devonfw-testing/files/1978065/site.zip)
I run all tests locally as I have no access to run any job on Jenkins yet. Allure results are included in zip file.
In general, there is one test with annotation ignore, so it is ignored.
There is one failing, but it is already inside test logic I didn't touch.
And at least there is one working only with firefox, so it failed on chrome.
Rest of tests is fine.

**Comment by lstefaniszyn** [comment]
@robert-duda-cap .    Majory of tests work great. 
00:02:41.515 Tests run: 32, Failures: 0, Errors: 1, Skipped: 1

http://10.40.234.40:8080/job/MrChecker-SDLC/job/MrChecker-ApplicationUnderTest-CI_pipeline/24/console

Only one test failed, please have a look :  com.capgemini.ntc.selenium.projectY.FileDownloadTest
FileDownloadTest.fileShouldBeDownloaded:45 ? Timeout Expected condition failed...

**Comment by robert-duda-cap** [comment]
Yes, right however it is still not a part of code from this PR. Locally works fine anyway. @pawel-szczesny , could you have a look at this test result, please?

**Pull request merged**
